version: 'latest'

services:
  app:
    build: .
    image: connectib
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes
  db:
    image: mysql:8.0
    restart: unless-stopped
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file:
      - .env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3306:3306
networks:
  app-network:
    driver: bridge
volumes:
  mysqldata:
